(() => {
  "use strict";
  const PAGE_W = 794, PAGE_H = 1123, GRID = 16;
  const clone = value => JSON.parse(JSON.stringify(value));
  const clamp = (v, min, max) => Math.max(min, Math.min(max, v));
  const snap = v => state.snap ? Math.round(v / GRID) * GRID : Math.round(v);
  const uid = () => `text-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
  const escapeHtml = text => text.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
  const $ = id => document.getElementById(id);

  const starters = [
    {id:"title",x:64,y:70,w:666,h:62,text:"未命名文件",fontSize:32,fontFamily:"Noto Serif TC",bold:true,italic:false,align:"left",color:"#17212b",lineHeight:1.2},
    {id:"meta",x:64,y:142,w:666,h:34,text:"A4 GRID DOCUMENT  ·  2026",fontSize:10,fontFamily:"Arial",bold:true,italic:false,align:"left",color:"#74808b",lineHeight:1.4},
    {id:"heading-1",x:64,y:224,w:206,h:44,text:"01  文件摘要",fontSize:15,fontFamily:"Noto Sans TC",bold:true,italic:false,align:"left",color:"#167d78",lineHeight:1.35},
    {id:"body-1",x:288,y:224,w:442,h:182,text:"點擊這段文字即可開始輸入。每個文字框都有自己的固定位置與大小，因此輸入內容時，不會推擠或移動頁面上的其他文字。\n\n拖曳文字框上方的把手可以自由移動；右下角則可以調整文字框大小。",fontSize:14,fontFamily:"Noto Sans TC",bold:false,italic:false,align:"left",color:"#263541",lineHeight:1.72},
    {id:"heading-2",x:64,y:454,w:206,h:44,text:"02  重點內容",fontSize:15,fontFamily:"Noto Sans TC",bold:true,italic:false,align:"left",color:"#167d78",lineHeight:1.35},
    {id:"body-2",x:288,y:454,w:442,h:246,text:"在這裡整理你的內容：\n\n• 使用左側工具新增文字框\n• 開啟吸附功能，快速對齊網格\n• 選取文字框後，可調整字型、尺寸與對齊\n• 完成後，從右上角匯出 Word 或 PDF",fontSize:14,fontFamily:"Noto Sans TC",bold:false,italic:false,align:"left",color:"#263541",lineHeight:1.78},
    {id:"quote",x:64,y:762,w:666,h:142,text:"「好的版面，讓每一段內容都待在它應該在的位置。」",fontSize:21,fontFamily:"Noto Serif TC",bold:false,italic:false,align:"center",color:"#17212b",lineHeight:1.6},
    {id:"footer",x:64,y:1040,w:666,h:28,text:"A4 · 210 × 297 mm                                            01",fontSize:9,fontFamily:"Arial",bold:false,italic:false,align:"left",color:"#98a0a8",lineHeight:1.4}
  ];
  const builtInTemplate={id:"built-in-summary",name:"A4 專案摘要",blocks:clone(starters),createdAt:"內建模板",builtIn:true};
  let savedTemplates=[];try{savedTemplates=JSON.parse(localStorage.getItem("paper-grid-templates-v4"))||[]}catch{}
  const state = {blocks:clone(starters),selectedId:"body-1",zoom:innerWidth<520?.44:innerWidth<820?.62:.72,grid:true,snap:true,history:[],future:[],drag:null,templates:[builtInTemplate,...savedTemplates],editingTemplateId:null,clipboard:null,findIndex:-1};
  try { const saved=JSON.parse(localStorage.getItem("paper-grid-studio-v4")); if(saved?.blocks?.length) state.blocks=saved.blocks; if(saved?.title) $("doc-title").value=saved.title; if(saved?.editingTemplateId&&state.templates.some(t=>t.id===saved.editingTemplateId))state.editingTemplateId=saved.editingTemplateId; } catch {}

  function selected(){ return state.blocks.find(b=>b.id===state.selectedId); }
  function save(){ clearTimeout(save.timer); save.timer=setTimeout(()=>localStorage.setItem("paper-grid-studio-v4",JSON.stringify({blocks:state.blocks,title:$("doc-title").value,editingTemplateId:state.editingTemplateId})),250); }
  function checkpoint(){ state.history.push(clone(state.blocks)); if(state.history.length>40) state.history.shift(); state.future=[]; updateUndo(); }
  function updateUndo(){ $("undo").disabled=!state.history.length; $("redo").disabled=!state.future.length; }
  function updateZoom(){ $("page").style.transform=`scale(${state.zoom})`; $("page-shell").style.width=`${PAGE_W*state.zoom}px`; $("page-shell").style.height=`${PAGE_H*state.zoom}px`; $("zoom-value").textContent=`${Math.round(state.zoom*100)}%`; }
  function styleTextarea(area,b){ const decorations=[b.underline?"underline":"",b.strike?"line-through":""].filter(Boolean).join(" ");Object.assign(area.style,{fontFamily:`"${b.fontFamily}",sans-serif`,fontSize:`${b.fontSize}px`,fontWeight:b.bold?"700":"400",fontStyle:b.italic?"italic":"normal",textDecoration:decorations||"none",textAlign:b.align,color:b.color,backgroundColor:b.highlight||"transparent",lineHeight:b.lineHeight,paddingLeft:`${8+(b.indent||0)}px`}); }
  function render(){
    document.querySelectorAll(".text-block").forEach(el=>el.remove());
    state.blocks.forEach(b=>{
      const block=document.createElement("div"); block.className=`text-block${b.id===state.selectedId?" selected":""}${b.locked?" locked":""}${b.border?" grid-cell":""}`; block.dataset.id=b.id; Object.assign(block.style,{left:`${b.x}px`,top:`${b.y}px`,width:`${b.w}px`,height:`${b.h}px`});
      if(b.id===state.selectedId){ const handle=document.createElement("button"); handle.className="drag-handle"; handle.ariaLabel="拖曳文字框"; handle.innerHTML="<i></i><i></i><i></i>"; handle.addEventListener("pointerdown",e=>startDrag(e,b,"move")); block.append(handle); }
      const area=document.createElement("textarea"); area.value=b.text; area.readOnly=!!b.locked; area.ariaLabel="文字內容"; styleTextarea(area,b); area.addEventListener("focus",()=>select(b.id)); area.addEventListener("input",()=>{b.text=area.value;save()}); block.append(area);
      if(b.id===state.selectedId&&!b.locked){ const resize=document.createElement("button"); resize.className="resize-handle"; resize.ariaLabel="調整文字框大小"; resize.addEventListener("pointerdown",e=>startDrag(e,b,"resize")); block.append(resize); }
      block.addEventListener("pointerdown",e=>{e.stopPropagation();if(state.selectedId!==b.id)select(b.id)}); $("page").append(block);
    });
    $("block-count").textContent=`${state.blocks.length} 個獨立文字框 · 無內容推擠`; renderInspector(); save();
  }
  function select(id){ if(state.selectedId===id)return; state.selectedId=id; render(); }
  function renderInspector(){
    const b=selected(), empty=$("empty-inspector"), props=$("properties"); empty.hidden=!!b; props.hidden=!b; $("lock").disabled=!b;
    renderRibbon();if(!b)return; $("font-family").value=b.fontFamily; $("font-size").value=b.fontSize; $("line-height").value=b.lineHeight; $("color").value=b.color; $("color-code").textContent=b.color.toUpperCase(); $("pos-x").value=Math.round(b.x); $("pos-y").value=Math.round(b.y); $("width").value=Math.round(b.w); $("height").value=Math.round(b.h); $("bold").classList.toggle("active",b.bold); $("italic").classList.toggle("active",b.italic); $("lock").classList.toggle("active",!!b.locked); document.querySelectorAll("[data-align]").forEach(btn=>btn.classList.toggle("active",btn.dataset.align===b.align));
  }
  function renderRibbon(){const b=selected(),ids=["cut-block","copy-block","font-smaller","font-larger","ribbon-bold","ribbon-italic","ribbon-underline","ribbon-strike","bullet-list","number-list","outdent","indent"];ids.forEach(id=>$(id).disabled=!b);$("paste-block").disabled=!state.clipboard;$("ribbon-font").disabled=!b;$("ribbon-size").disabled=!b;$("ribbon-line-height").disabled=!b;if(!b)return;$("ribbon-font").value=b.fontFamily;$("ribbon-size").value=b.fontSize;$("ribbon-line-height").value=String([1,1.2,1.5,1.75,2].reduce((a,v)=>Math.abs(v-b.lineHeight)<Math.abs(a-b.lineHeight)?v:a,1));$("ribbon-color").value=b.color||"#263541";$("ribbon-highlight").value=b.highlight||"#fff2a8";$("ribbon-bold").classList.toggle("active",!!b.bold);$("ribbon-italic").classList.toggle("active",!!b.italic);$("ribbon-underline").classList.toggle("active",!!b.underline);$("ribbon-strike").classList.toggle("active",!!b.strike);document.querySelectorAll("[data-ribbon-align]").forEach(btn=>btn.classList.toggle("active",btn.dataset.ribbonAlign===b.align))}
  function saveNow(){localStorage.setItem("paper-grid-studio-v4",JSON.stringify({blocks:state.blocks,title:$("doc-title").value,editingTemplateId:state.editingTemplateId}));notify("文件已儲存")}
  function newDocument(){if(!confirm("建立新文件會清除目前畫布，確定繼續嗎？"))return;checkpoint();state.editingTemplateId=null;state.blocks=[{id:uid(),x:64,y:64,w:666,h:64,text:"未命名文件",fontSize:32,fontFamily:"Noto Serif TC",bold:true,italic:false,align:"left",color:"#17212b",lineHeight:1.2}];state.selectedId=state.blocks[0].id;$("doc-title").value="未命名文件";updateEditingUI();render();saveNow()}
  function saveProject(){const title=$("doc-title").value||"A4文件",data={format:"paper-grid-a4",version:1,title,blocks:state.blocks};download(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),`${title}.a4doc`);notify("可編輯專案檔已下載")}
  function openProjectFile(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(data.format!=="paper-grid-a4"||!Array.isArray(data.blocks))throw new Error();checkpoint();state.editingTemplateId=null;state.blocks=data.blocks;state.selectedId=state.blocks[0]?.id||"";$("doc-title").value=data.title||"已開啟文件";updateEditingUI();render();saveNow()}catch{notify("無法開啟此專案檔")}};reader.readAsText(file)}
  function findMatches(){const term=$("find-text").value;if(!term)return[];return state.blocks.map((b,index)=>({b,index,count:b.text.split(term).length-1})).filter(item=>item.count>0)}
  function findNext(){const matches=findMatches();if(!matches.length){$("find-result").textContent="找不到符合的文字。";return}state.findIndex=(state.findIndex+1)%matches.length;state.selectedId=matches[state.findIndex].b.id;render();$("find-result").textContent=`找到 ${matches.reduce((n,m)=>n+m.count,0)} 處，目前位於第 ${state.findIndex+1} 個文字框。`}
  function replaceAll(){const term=$("find-text").value,replacement=$("replace-text").value;if(!term)return;const matches=findMatches(),total=matches.reduce((n,m)=>n+m.count,0);if(!total){$("find-result").textContent="找不到符合的文字。";return}checkpoint();state.blocks.forEach(b=>b.text=b.text.split(term).join(replacement));render();$("find-result").textContent=`已完成 ${total} 處取代。`}
  function update(changes,history=true){ const b=selected(); if(!b)return; if(history)checkpoint(); Object.assign(b,changes); render(); }
  function addText(){ checkpoint(); const n=state.blocks.length,b={id:uid(),x:80+(n%3)*16,y:180+(n%10)*48,w:320,h:96,text:"在此輸入文字",fontSize:14,fontFamily:"Noto Sans TC",bold:false,italic:false,align:"left",color:"#263541",lineHeight:1.6}; state.blocks.push(b); state.selectedId=b.id; render(); }
  function addCell(){ checkpoint(); const n=state.blocks.length,b={id:uid(),x:80+(n%3)*16,y:180+(n%10)*48,w:208,h:64,text:"輸入內容",fontSize:13,fontFamily:"Noto Sans TC",bold:false,italic:false,align:"center",color:"#263541",lineHeight:1.4,border:true}; state.blocks.push(b); state.selectedId=b.id; render(); }
  function duplicate(){ const b=selected();if(!b)return;checkpoint();const copy={...clone(b),id:uid(),x:clamp(b.x+GRID,0,PAGE_W-b.w),y:clamp(b.y+GRID,0,PAGE_H-b.h),locked:false};state.blocks.push(copy);state.selectedId=copy.id;render() }
  function remove(){ if(!selected())return;checkpoint();state.blocks=state.blocks.filter(b=>b.id!==state.selectedId);state.selectedId="";render() }
  function copyBlock(){const b=selected();if(!b)return;state.clipboard=clone(b);notify("文字框已複製");renderRibbon()}
  function cutBlock(){const b=selected();if(!b)return;state.clipboard=clone(b);remove();notify("文字框已剪下")}
  function pasteBlock(){if(!state.clipboard)return;checkpoint();const b={...clone(state.clipboard),id:uid(),x:clamp((state.clipboard.x||0)+GRID,0,PAGE_W-state.clipboard.w),y:clamp((state.clipboard.y||0)+GRID,0,PAGE_H-state.clipboard.h),locked:false};state.blocks.push(b);state.selectedId=b.id;render();notify("文字框已貼上")}
  function toggleList(type){const b=selected();if(!b)return;checkpoint();const lines=b.text.split("\n"),bullet=/^•\s+/,number=/^\d+[.)]\s+/;const matcher=type==="bullet"?bullet:number,all=lines.filter(Boolean).every(line=>matcher.test(line));let count=1;b.text=lines.map(line=>{if(!line)return line;if(all)return line.replace(matcher,"");const clean=line.replace(bullet,"").replace(number,"");return type==="bullet"?`• ${clean}`:`${count++}. ${clean}`}).join("\n");render()}
  function startDrag(e,b,type){ if(b.locked)return;e.preventDefault();e.stopPropagation();checkpoint();state.drag={id:b.id,type,startX:e.clientX,startY:e.clientY,block:clone(b)};e.currentTarget.setPointerCapture(e.pointerId) }
  window.addEventListener("pointermove",e=>{ const d=state.drag;if(!d)return;const b=state.blocks.find(x=>x.id===d.id),dx=(e.clientX-d.startX)/state.zoom,dy=(e.clientY-d.startY)/state.zoom;if(d.type==="move"){b.x=clamp(snap(d.block.x+dx),0,PAGE_W-d.block.w);b.y=clamp(snap(d.block.y+dy),0,PAGE_H-d.block.h)}else{b.w=clamp(snap(d.block.w+dx),80,PAGE_W-d.block.x);b.h=clamp(snap(d.block.h+dy),40,PAGE_H-d.block.y)}render()});
  window.addEventListener("pointerup",()=>state.drag=null);

  $("add-text").onclick=addText; $("add-cell").onclick=addCell; $("duplicate").onclick=duplicate; $("delete").onclick=remove;
  $("undo").onclick=()=>{if(!state.history.length)return;state.future.unshift(clone(state.blocks));state.blocks=state.history.pop();state.selectedId=state.blocks[0]?.id||"";render();updateUndo()};
  $("redo").onclick=()=>{if(!state.future.length)return;state.history.push(clone(state.blocks));state.blocks=state.future.shift();state.selectedId=state.blocks[0]?.id||"";render();updateUndo()};
  $("toggle-grid").onclick=()=>{state.grid=!state.grid;$("page").classList.toggle("show-grid",state.grid);$("toggle-grid").querySelector("i").classList.toggle("active",state.grid)};
  $("toggle-snap").onclick=()=>{state.snap=!state.snap;$("toggle-snap").querySelector("i").classList.toggle("active",state.snap);$("snap-status").textContent=state.snap?"吸附中":"自由移動"};
  $("zoom-out").onclick=()=>{state.zoom=clamp(state.zoom-.08,.38,1.2);updateZoom()}; $("zoom-in").onclick=()=>{state.zoom=clamp(state.zoom+.08,.38,1.2);updateZoom()};
  $("mobile-tools").onclick=e=>{e.stopPropagation();$("sidebar").classList.toggle("open")}; $("page").addEventListener("pointerdown",e=>{if(e.target===$("page")||e.target.classList.contains("safe-area")){state.selectedId="";render()}});
  $("doc-title").oninput=save; $("export-toggle").onclick=e=>{e.stopPropagation();$("export-menu").hidden=!$("export-menu").hidden}; document.addEventListener("click",()=>$("export-menu").hidden=true);
  $("font-family").onchange=e=>update({fontFamily:e.target.value}); $("font-size").onchange=e=>update({fontSize:clamp(+e.target.value,8,72)}); $("line-height").onchange=e=>update({lineHeight:clamp(+e.target.value,1,2.5)}); $("color").oninput=e=>update({color:e.target.value});
  $("bold").onclick=()=>update({bold:!selected().bold}); $("italic").onclick=()=>update({italic:!selected().italic}); $("lock").onclick=()=>update({locked:!selected().locked}); document.querySelectorAll("[data-align]").forEach(btn=>btn.onclick=()=>update({align:btn.dataset.align}));
  [["pos-x","x",0,()=>PAGE_W-selected().w],["pos-y","y",0,()=>PAGE_H-selected().h],["width","w",80,()=>PAGE_W-selected().x],["height","h",40,()=>PAGE_H-selected().y]].forEach(([id,key,min,max])=>$(id).onchange=e=>update({[key]:clamp(+e.target.value,min,max())}));
  $("new-document").onclick=newDocument;$("save-now").onclick=saveNow;$("save-project").onclick=saveProject;$("open-project").onclick=()=>$("project-file").click();$("project-file").onchange=e=>{if(e.target.files[0])openProjectFile(e.target.files[0]);e.target.value=""};
  $("cut-block").onclick=cutBlock;$("copy-block").onclick=copyBlock;$("paste-block").onclick=pasteBlock;
  $("ribbon-font").onchange=e=>update({fontFamily:e.target.value});$("ribbon-size").onchange=e=>update({fontSize:clamp(+e.target.value,8,72)});$("font-smaller").onclick=()=>update({fontSize:clamp(selected().fontSize-1,8,72)});$("font-larger").onclick=()=>update({fontSize:clamp(selected().fontSize+1,8,72)});$("ribbon-bold").onclick=()=>update({bold:!selected().bold});$("ribbon-italic").onclick=()=>update({italic:!selected().italic});$("ribbon-underline").onclick=()=>update({underline:!selected().underline});$("ribbon-strike").onclick=()=>update({strike:!selected().strike});$("ribbon-color").oninput=e=>update({color:e.target.value});$("ribbon-highlight").oninput=e=>update({highlight:e.target.value});
  $("bullet-list").onclick=()=>toggleList("bullet");$("number-list").onclick=()=>toggleList("number");$("outdent").onclick=()=>update({indent:clamp((selected().indent||0)-16,0,96)});$("indent").onclick=()=>update({indent:clamp((selected().indent||0)+16,0,96)});document.querySelectorAll("[data-ribbon-align]").forEach(btn=>btn.onclick=()=>update({align:btn.dataset.ribbonAlign}));$("ribbon-line-height").onchange=e=>update({lineHeight:+e.target.value});
  $("open-find").onclick=()=>{$("find-panel").hidden=false;$('find-text').focus()};$("close-find").onclick=()=>$("find-panel").hidden=true;$("find-next").onclick=findNext;$("replace-all").onclick=replaceAll;$("find-text").addEventListener("keydown",e=>{if(e.key==="Enter")findNext()});
  document.addEventListener("keydown",e=>{const key=e.key.toLowerCase(),command=e.ctrlKey||e.metaKey,typing=/INPUT|TEXTAREA|SELECT/.test(e.target.tagName);if(command&&key==="s"){e.preventDefault();saveNow();return}if(command&&key==="f"){e.preventDefault();$("open-find").click();return}if(command&&key==="z"){e.preventDefault();e.shiftKey?$("redo").click():$("undo").click();return}if(command&&selected()&&["b","i","u"].includes(key)){e.preventDefault();$(key==="b"?"ribbon-bold":key==="i"?"ribbon-italic":"ribbon-underline").click();return}if(typing)return;if((e.key==="Delete"||e.key==="Backspace")&&selected()){e.preventDefault();remove()}if(command&&key==="d"){e.preventDefault();duplicate()}if(command&&key==="c"){e.preventDefault();copyBlock()}if(command&&key==="x"){e.preventDefault();cutBlock()}if(command&&key==="v"&&state.clipboard){e.preventDefault();pasteBlock()}});

  function notify(message){$("toast").querySelector("b").textContent=message;$("toast").hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$("toast").hidden=true,2400)}
  function saveTemplateStore(){localStorage.setItem("paper-grid-templates-v4",JSON.stringify(state.templates.filter(t=>!t.builtIn)))}
  function renderTemplates(){
    const list=$("template-list");list.innerHTML="";$("template-count").textContent=state.templates.length;$("template-empty").hidden=state.templates.length>0;
    state.templates.forEach(template=>{
      const card=document.createElement("article");card.className="template-card";
      const thumb=document.createElement("div");thumb.className="template-thumb";
      template.blocks.forEach(b=>{const item=document.createElement("div");item.className="template-preview-item";item.textContent=b.text;Object.assign(item.style,{left:`${b.x/PAGE_W*82}px`,top:`${b.y/PAGE_H*116}px`,width:`${b.w/PAGE_W*82}px`,height:`${b.h/PAGE_H*116}px`,color:b.color,fontWeight:b.bold?"700":"400",textAlign:b.align,border:b.border?"1px solid #9aa8ab":"0"});thumb.append(item)});
      const info=document.createElement("div");info.className="template-info";const title=document.createElement("h3");title.textContent=template.name;const meta=document.createElement("p");meta.textContent=`${template.blocks.length} 個文字框${template.builtIn?" · 官方版型":""}`;const time=document.createElement("time");time.textContent=template.createdAt;const actions=document.createElement("div");actions.className="template-actions";const use=document.createElement("button");use.className="use-template";use.textContent="建立副本";use.onclick=()=>useTemplate(template.id);actions.append(use);
      if(!template.builtIn){const edit=document.createElement("button");edit.className="edit-template";edit.textContent="編輯";edit.onclick=()=>editTemplate(template.id);actions.append(edit);const del=document.createElement("button");del.className="delete-template";del.title="刪除模板";del.textContent="×";del.onclick=()=>{if(confirm(`確定刪除「${template.name}」模板嗎？`)){state.templates=state.templates.filter(t=>t.id!==template.id);if(state.editingTemplateId===template.id){state.editingTemplateId=null;updateEditingUI()}saveTemplateStore();renderTemplates();notify("模板已刪除")}};actions.append(del)}
      info.append(title,meta,time,actions);card.append(thumb,info);list.append(card);
    });
  }
  function openTemplates(){renderTemplates();$("template-panel").hidden=false;$("template-scrim").hidden=false;$("sidebar").classList.remove("open")}
  function closeTemplates(){$("template-panel").hidden=true;$("template-scrim").hidden=true}
  function saveAsTemplate(){const field=$("template-name"),name=field.value.trim()||`${$("doc-title").value.trim()||"未命名文件"} 模板`;state.templates.push({id:uid(),name,blocks:clone(state.blocks),createdAt:new Date().toLocaleDateString("zh-TW"),builtIn:false});saveTemplateStore();field.value="";renderTemplates();notify(`已儲存模板「${name}」`)}
  function updateEditingUI(){const editing=!!state.editingTemplateId;$("save-template-changes").hidden=!editing;$("save-status").textContent=editing?"正在編輯模板":"已自動儲存";document.body.classList.toggle("editing-template",editing)}
  function useTemplate(id){const template=state.templates.find(t=>t.id===id);if(!template)return;checkpoint();state.editingTemplateId=null;state.blocks=clone(template.blocks).map((b,index)=>({...b,id:`${uid()}-${index}`}));state.selectedId=state.blocks[0]?.id||"";$("doc-title").value=`${template.name} - 副本`;updateEditingUI();closeTemplates();render();save();notify("已建立可編輯的模板副本")}
  function editTemplate(id){const template=state.templates.find(t=>t.id===id&&!t.builtIn);if(!template)return;checkpoint();state.editingTemplateId=id;state.blocks=clone(template.blocks).map((b,index)=>({...b,id:`${uid()}-${index}`}));state.selectedId=state.blocks[0]?.id||"";$("doc-title").value=template.name;updateEditingUI();closeTemplates();render();save();notify("正在編輯模板，完成後請儲存變更")}
  function saveTemplateChanges(){const template=state.templates.find(t=>t.id===state.editingTemplateId);if(!template)return;const name=$("doc-title").value.trim()||template.name;template.name=name;template.blocks=clone(state.blocks);template.createdAt=`更新於 ${new Date().toLocaleDateString("zh-TW")}`;state.editingTemplateId=null;saveTemplateStore();updateEditingUI();renderTemplates();save();notify(`模板「${name}」已更新`)}
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
  function exportWord(){try{const title=$("doc-title").value||"A4文件",bytes=window.PaperGridDocx.buildDocx(state.blocks,title);download(new Blob([bytes],{type:"application/vnd.openxmlformats-officedocument.wordprocessingml.document"}),`${title}.docx`);notify("Word DOCX 已匯出")}catch(error){console.error(error);notify("Word 匯出失敗")}}
  function wrapText(ctx,text,maxWidth){const lines=[];text.split("\n").forEach(paragraph=>{if(paragraph===""){lines.push("");return}let line="";for(const char of paragraph){const test=line+char;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=char}else line=test}lines.push(line)});return lines}
  function renderCanvas(){const scale=2,canvas=document.createElement("canvas");canvas.width=PAGE_W*scale;canvas.height=PAGE_H*scale;const ctx=canvas.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);state.blocks.forEach(b=>{ctx.save();ctx.beginPath();ctx.rect(b.x*scale,b.y*scale,b.w*scale,b.h*scale);ctx.clip();if(b.highlight){ctx.fillStyle=b.highlight;ctx.fillRect(b.x*scale,b.y*scale,b.w*scale,b.h*scale)}if(b.border){ctx.strokeStyle="#9aa8ab";ctx.lineWidth=1.5*scale;ctx.strokeRect(b.x*scale+.75*scale,b.y*scale+.75*scale,b.w*scale-1.5*scale,b.h*scale-1.5*scale)}ctx.fillStyle=b.color;ctx.font=`${b.italic?"italic ":""}${b.bold?"700":"400"} ${b.fontSize*scale}px "${b.fontFamily}",sans-serif`;ctx.textBaseline="top";ctx.textAlign=b.align==="justify"?"left":b.align;const pad=8*scale,indent=(b.indent||0)*scale,x=b.align==="center"?(b.x+b.w/2)*scale:b.align==="right"?(b.x+b.w)*scale-pad:b.x*scale+pad+indent,y=b.y*scale+pad,max=b.w*scale-pad*2-indent,lineH=b.fontSize*b.lineHeight*scale;wrapText(ctx,b.text,max).forEach((line,i)=>{const lineY=y+i*lineH;ctx.fillText(line,x,lineY,max);if(b.underline||b.strike){const width=Math.min(ctx.measureText(line).width,max),start=b.align==="center"?x-width/2:b.align==="right"?x-width:x;ctx.beginPath();ctx.lineWidth=Math.max(1,scale);if(b.underline){ctx.moveTo(start,lineY+b.fontSize*scale*1.05);ctx.lineTo(start+width,lineY+b.fontSize*scale*1.05)}if(b.strike){ctx.moveTo(start,lineY+b.fontSize*scale*.55);ctx.lineTo(start+width,lineY+b.fontSize*scale*.55)}ctx.strokeStyle=b.color;ctx.stroke()}});ctx.restore()});return canvas}
  function makePdf(dataUrl){const binary=atob(dataUrl.split(",")[1]),image=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)image[i]=binary.charCodeAt(i);const enc=new TextEncoder(),chunks=[],offsets=[0];let offset=0;const push=x=>{const bytes=typeof x==="string"?enc.encode(x):x;chunks.push(bytes);offset+=bytes.length};const obj=(id,body)=>{offsets[id]=offset;push(`${id} 0 obj\n`);typeof body==="function"?body():push(body);push("\nendobj\n")};push("%PDF-1.4\n");obj(1,"<< /Type /Catalog /Pages 2 0 R >>");obj(2,"<< /Type /Pages /Kids [3 0 R] /Count 1 >>");obj(3,"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>");obj(4,()=>{push(`<< /Type /XObject /Subtype /Image /Width ${PAGE_W*2} /Height ${PAGE_H*2} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${image.length} >>\nstream\n`);push(image);push("\nendstream")});const content="q\n595.28 0 0 841.89 0 0 cm\n/Im0 Do\nQ";obj(5,`<< /Length ${content.length} >>\nstream\n${content}\nendstream`);const xref=offset;push("xref\n0 6\n0000000000 65535 f \n");for(let i=1;i<=5;i++)push(`${String(offsets[i]).padStart(10,"0")} 00000 n \n`);push(`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`);const out=new Uint8Array(chunks.reduce((n,c)=>n+c.length,0));let pos=0;chunks.forEach(c=>{out.set(c,pos);pos+=c.length});return new Blob([out],{type:"application/pdf"})}
  function exportPdf(){try{const title=$("doc-title").value||"A4文件",jpeg=renderCanvas().toDataURL("image/jpeg",.96);download(makePdf(jpeg),`${title}.pdf`);notify("PDF 檔已匯出")}catch(error){console.error(error);notify("PDF 匯出失敗")}}
  $("export-word").onclick=e=>{e.stopPropagation();exportWord();$("export-menu").hidden=true}; $("export-pdf").onclick=e=>{e.stopPropagation();exportPdf();$("export-menu").hidden=true};
  $("open-templates").onclick=openTemplates;$("mobile-templates").onclick=e=>{e.stopPropagation();openTemplates()};$("close-templates").onclick=closeTemplates;$("template-scrim").onclick=closeTemplates;$("save-template").onclick=saveAsTemplate;$("template-name").addEventListener("keydown",e=>{if(e.key==="Enter")saveAsTemplate()});$("save-template-changes").onclick=saveTemplateChanges;
  updateZoom(); updateUndo();updateEditingUI(); render();renderTemplates();
})();
